version: '3.7'
services:
  nodejs-api:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    command: npm start
    env_file: ./.env
    ports:
      - "8080:8080"
    container_name: nodejs-api